version: "3"
services:
  nginx:
    image: bitnami/nginx:1.19
    user: root
    ports:
      - 8080:8080
      - 8443:8443
    restart: always
    volumes:
      - ./dockers/nginx/nginx:/bitnami/nginx